name: crypt_chat
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.0.3
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  firebase_core: ^0.7.0
  shared_preferences: ^0.5.12+4
  encrypt: ^4.1.0
  google_fonts: ^1.1.2
  image_picker: ^0.6.7+4
  firebase_storage: ^7.0.0
  location: ^3.2.4 #^3.2.4

  #geolocator: ^6.2.0
  #google_maps_flutter: ^2.0.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  webview_flutter: ^2.0.0
  flutter_screen_lock: ^5.0.12
  flutter_session: ^0.1.1
  flutter_secure_storage: ^4.2.1
  dart_jsonwebtoken: ^1.6.2
  local_auth: ^0.6.3+4
  flutter_windowmanager: ^0.2.0
  day_night_switcher: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/

